<?php
/*
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
    define ('METHOD_IS_NOT_CALLABLE',               'Cannot CALL method. The passed method cannot be called from this context!' );
    define ('CANNOT_SET_PHP_INCLUDE_PATH',          'Cannot set include PATH. This is a LOW_LEVEL bug!'                         );
    define ('CANNOT_OUTPUT_ERROR_SCREEN',           'Cannot output error screen. This is a LOW_LEVEL bug!'                      );
    define ('CANNOT_SET_INI_PARAMS',                'Cannot set INI PHP Options. Halting ALL actions. Check INI!'               );
    define ('CANNOT_RETURN_SYSTEM_LOAD_AVG',        'Cannot return system average load. Is this a Linux system?'                );
    define ('CANNOT_SET_OUTPUT_WORKER',             'Cannot set Output Buffer Callback Worker Method!'                          );
    define ('CANNOT_SET_OUTPUT_WORKER_FIX',         'This means that the method is not callable.'                               );
    define ('CANNOT_SET_ERROR_CATCHER',             'Cannot set Output Buffer Error Catcher Method!'                            );
    define ('CANNOT_SET_ERROR_CATCHER_FIX',         'This means that the method is not callable.'                               );
    define ('HEADERS_ALREADY_SENT',                 'Cannot add header information. Headers already sent!'                      );
    define ('HEADERS_ALREADY_SENT_FIX',             'Something is wrong with output buffering!'                                 );
    define ('CANNOT_ESCAPE_STRING',                 'Could not escape string. Something is wrong'                               );
    define ('CANNOT_ESCAPE_STRING_FIX',             'Check to see if it is a string'                                            );
    define ('UNKNOWN_DATA_TYPE',                    'We encountered an unknown data-type.'                                      );
    define ('UNKNOWN_DATA_TYPE_FIX',                'This is an error beyond our powers.'                                       );
    define ('INVALID_LENGTH',                       'Checked variable has an invalid lenght.'                                   );
    define ('INVALID_LENGTH_FIX',                   'Check that the length is in the in proper range!'                          );
    define ('FILE_DOESNT_EXIST',                    'The file does not exists.'                                                 );
    define ('FILE_DOESNT_EXIST_FIX',                'Please repair this error by giving the correct path.'                      );
    define ('CANNOT_WRITE_HTACCESS_FILE',	    	'Cannot write .htaccess file to the root directory!'			            );
    define ('CANNOT_WRITE_HTACCESS_FILE_FIX',       'Please make sure that you have set proper permissions!'			        );
    define ('CANNOT_WRITE_CACHE_DIR',               'The cache directory (CACHE_DIR) cannot be written!'                        );
    define ('CANNOT_WRITE_LOG_DIR',                 'The logging directory (LOG_DIR) cannot be written!'                        );
    define ('CANNOT_WRITE_UPLOAD_DIR',              'The upload directory (UPLOAD_DIR) cannot be written!'                      );
    define ('CANNOT_WRITE_TEMP_DIR',                'The temporay directory (TEMP_DIR) cannot be written!'                      );
    define ('CANNOT_WRITE_FIX_PERMISSIONS',         'Please fix the permissions given on the file or directory!'                );
    define ('STRINGS_NOT_EQUAL_SIZE',               'Strings are not of equal size.'                                            );
    define ('STRINGS_NOT_EQUAL_SIZE_FIX',           'It does not make sense to compare them if they differ in size.'            );
    define ('INVALID_DATA_TYPE',                    'Unknown or invalid data type.'                                             );
    define ('INVALID_DATA_TYPE_FIX',                'Make sure you pass proper variables and you are doing the right stuff.'    );
    define ('FATAL_ERROR',                          'We caught a FATAL error.'                                                  );
    define ('FATAL_ERROR_CHECK_LOG',                'Check log files for more info than we can provide here.'                   );
    define ('FATAL_CANNOT_SET_ERROR_REPORTING',     'Cannot set error reporting!');
    define ('FATAL_CANNOT_SET_CACHE_EXPIRE',        'Cannot set session cache expire!');
    define ('FATAL_CANNOT_SET_SCRIPT_TIME_LIMIT',   'Cannot set script max execution time!');
    define ('FATAL_CANNOT_SET_DISPLAY_ERRORS',      'Cannot set display errors to a true value!');
    define ('FATAL_CANNOT_SET_MEMORY_LIMIT',        'Cannot set memory limit!');
    define ('WARNING_ERROR',                        'We caught a warning.'                                                      );
    define ('WARNING_ERROR_FIX',                    'Please fix this warning before going further.'                             );
    define ('NOTICE_ERROR',                         'We caught a notice.'                                                       );
    define ('NOTICE_ERROR_FIX',                     'You can ignore it, but we ask (ok, FORCE!) you not to.'                    );
    define ('CANNOT_START_SESSION',                 'Cannot start session.'                                                     );
    define ('CANNOT_START_SESSION_FIX',             'Fix this error if you want session support.'                               );
    define ('SESSION_ALREADY_STARTED',              'Session already started.'                                                  );
    define ('SESSION_ALREADY_STARTED_FIX',          'Will not start a second session. Fix your code!'                           );
    define ('SESSION_ALREADY_STOP',                 'Session has been already destroyed.'                                       );
    define ('SESSION_ALREADY_STOP_FIX',             'We cannot destroy an unstarted session.'                                   );
    define ('CANNOT_PUSH_OB_VAR',                   'Cannot push variable in replacement array.'                                );
    define ('CANNOT_PUSH_OB_VAR_FIX',               'You may be out of memory, or something bad has happened.'                  );
    define ('EMPTY_STRING_IN_CONVERSION',           'We detected an empty string in conversion.'                                );
    define ('EMPTY_STRING_IN_CONVERSION_FIX',       'Please fix this issue. It is a coding error.'                              );
    define ('VAR_NOT_STRING',                       'Checked variable is not a string.'                                         );
    define ('VAR_NOT_STRING_FIX',                   'Make sure the variable is a string.'                                       );
    define ('VAR_NOT_INT',                          'Checked variable is not an integer type.'                                  );
    define ('VAR_NOT_INT_FIX',                      'Make sure the variable is an integer.'                                     );
    define ('VAR_NOT_OBJECT',                       'Checked variable is not an object.'                                        );
    define ('VAR_NOT_OBJECT_FIX',                   'Make sure you are using a proper object.'                                  );
    define ('VAR_NOT_RESOURCE',                     'Checked variable is not a resource.'                                       );
    define ('VAR_NOT_RESOURCE_FIX',                 'Make sure you are using this resource in the proper context.'              );
    define ('EMPTY_STRING_IN_CHECK',                'The checked variable was empty.'                                           );
    define ('EMPTY_STRING_IN_CHECK_FIX',            'Fix this issue before going further.'                                      );
    define ('VAR_NOT_SET',                          'Checked variable is not set.'                                              );
    define ('VAR_NOT_SET_FIX',                      'Set this variable to a value before checking.'                             );
    define ('ELEMENT_NOT_IN_ARRAY',                 'The element you searched for in the array was not found.'                  );
    define ('ELEMENT_NOT_IN_ARRAY_FIX',             'Make sure you have a proper array.'                                        );
    define ('DEBUG_ERROR_SENT',                     'We received a debug request.'                                              );
    define ('DEBUG_ERROR_SENT_FIX',                 'Check the info bellow or above for the cause of your problems.'            );
    define ('CANNOT_CHANGE_ARRAY_KEY_CASE',         'Cannot change array key case. Check your code!'                            );
    define ('NO_PROPER_CASE_STRING',                'The conversion string is not of type: LOWER or UPPER.'                     );
    define ('NO_PROPER_CASE_STRING_FIX',            'Cannot detect string case. Please make sure the variable is a string.'     );
    define ('EMPTY_VARIABLE',                       'Checked variable is not empty.'                                            );
    define ('EMPTY_VARIABLE_FIX',                   'Please fix this issue now.'                                                );
    define ('ARRAY_NOT_EQUAL_SIZE',                 'Arrays are not of equal size.'                                             );
    define ('ARRAY_NOT_EQUAL_SIZE_FIX',             'Please make sure arrays are of equal size.'                                );
    define ('VARS_DIFFER',                          'Compared variables are not the same.'                                      );
    define ('VARS_DIFFER_FIX',                      'Should you try to use them that way it will be a source of bugs.'          );
    define ('CANNOT_COUNT_ARRAY_VALUES',            'Coult not count array values and their frequency. Something is wrong!'     );
    define ('CANNOT_COUNT_ARRAY_VALUES_FIX',        'Please make sure you are tring to count values from an array.'             );
    define ('RESULT_NOT_ARRAY',                     'Result is not an array.'                                                   );
    define ('RESULT_NOT_ARRAY_FIX',                 'Please make sure this is not a framework bug.'                             );
    define ('COULD_NOT_FILL_ARRAY',                 'Could not fill array, due to lack of memory or some other cause.'          );
    define ('ARRAY_KEY_DOESNT_EXIST',               'Array key does not exist!'                                                 );
    define ('COULD_NOT_WRITE_LOG',                  'Could not write in syslog.'                                                );
    define ('COULD_NOT_WRITE_LOG_FIX',              'Check file permissions or that you have enough space in /var partition.'   );
    define ('PLEASE_FIX_THIS',                      'Please fix this before going any further.'                                 );
    define ('SESSION_VARS_ARE_NOT_THE_SAME',        'Saved variables in _SESSION are not the same.'                             );
    define ('SESSION_VARS_ARE_NOT_THE_SAME_FIX',    'Please fix this issue before going any further.'                           );
    define ('SESSION_VAR_ALREADY_SET',              'Sesion variable is already set. Will not overwrite variable!'              );
    define ('SESSION_VAR_ALREADY_SET_FIX',          'Make sure you are not rewriting session variables.'                        );
    define ('CANNOT_MODIFY_SESSION_VAR',            'Cannot modify _SESSION var, because it is not set.'                        );
    define ('CANNOT_MODIFY_SESSION_VAR_FIX',        'Fis this little issue before going further.'                               );
    define ('SESSION_VAR_NOT_SET',                  'Session var not set.'                                                      );
    define ('SESSION_VAR_NOT_SET_FIX',              'Please set a session var before trying to unset it.'                       );
    define ('NOTICE_USER_ERROR',                    'PHP caused an E_USER_ERROR.'                                               );
    define ('NOTICE_USER_ERROR_FIX',                'Fix the indicated issue before going further.'                             );
    define ('WARNING_USER_ERROR',                   'PHP caused an E_USER_WARNING.'                                             );
    define ('WARNING_USER_ERROR_FIX',               'Fix the indicated issue before going further.'                             );
    define ('NOTICE_USER_NOTICE',                   'PHP caused an E_USER_NOTICE.'                                              );
    define ('NOTICE_USER_NOTICE_FIX',               'Fix the indicated issue before going further.'                             );
    define ('NOTICE_RECOVERABLE_ERROR',             'PHP caused an E_RECOVERABLE.'                                              );
    define ('NOTICE_RECOVERABLE_ERROR_FIX',         'Fix the indicated issue before going further.'                             );
    define ('NOTICE_ERROR_ALL',                     'PHP caused an E_ALL.'                                                      );
    define ('NOTICE_ERROR_ALL_FIX',                 'Fix the indicated issue before going further.'                             );
    define ('SYSTEM_LOAD_TOO_HIGH',                 'System load is to high.'                                                   );
    define ('SYSTEM_LOAD_TOO_HIGH_FIX',             'Check back later, when the load will hopefully reduce.'                    );
    define ('CANNOT_DETERMINE_SYS_AVG',             'Cannot determine system load-average.'                                     );
    define ('CANNOT_DETERMINE_SYS_AVG_FIX',         'Why does this happen? On Linux it does not!'                               );
    define ('CANNOT_PAD_ARRAY',                     'Cannot pad array.'                                                         );
    define ('CANNOT_PAD_ARRAY_FIX',                 'Usually, this means that the variable is not an array. Fix it!'            );
    define ('CANNOT_POP_FROM_ARRAY',                'Cannot pop from array.'                                                    );
    define ('CANNOT_POP_FROM_ARRAY_FIX',            'This means that the array may be empty.'                                   );
    define ('COULD_NOT_CHOOSE_RANDOM_ARRAY',        'Could not choose random values from array.'                                );
    define ('COULD_NOT_CHOOSE_RANDOM_ARRAY_FIX',    'Please recheck your code.'                                                 );
    define ('CANNOT_REVERSE_ARRAY',                 'Cannot reverse array.'                                                     );
    define ('CANNOT_REVERSE_ARRAY_FIX',             'May be empty or some other strange error.'                                 );
    define ('VAR_NOT_BOOL',                         'Checked variable not boolean.'                                             );
    define ('VAR_NOT_BOOL_FIX',                     'Please make sure you are using a boolean.'                                 );
    define ('VAR_IS_NOT_RESOURCE',                  'Checked variable is not a resource.'                                       );
    define ('VAR_IS_NOT_RESOURCE_FIX',              'Please make sure you are using the resource in the right context.'         );
    define ('GLOBAL_ARRAYS_NOT_SET',                'Global arrays are not set.'                                                );
    define ('GLOBAL_ARRAYS_NOT_SET_FIX',            'Please make sure that $GLOBALS[A] && $GLOBALS[B] are arrays.'              );
    define ('VAR_NOT_ARRAY',                        'Returned variable is not an array.'                                        );
    define ('VAR_NOT_ARRAY_FIX',                    'This may be a framework bug, but please double-check!'                     );
    define ('VAR_NOT_BOOLEAN',                      'Checked/returned variable is not a boolean value.'                         );
    define ('VAR_NOT_BOOLEAN_FIX',                  'Make sure you did not pass a string or any other kind of variable.'        );
    define ('VAR_NOT_FLOAT',                        'Checked/returned variable is no float.'                                    );
    define ('VAR_NOT_FLOAT_FIX',                    'Make sure you pass a float, or the math you wanted returns a float.'       );
    define ('CANNOT_CHANGE_ARRAY_KEY_CASE_FIX',     'Make sure the array has string-based keys.'                                );
    define ('CANNOT_SPLIT_ARRAY',                   'Cannot split array.'                                                       );
    define ('CANNOT_SPLIT_ARRAY_FIX',               'Please make sure you are spliting an array and nothing else.'              );
    define ('CANNOT_COMBINE_ARRAYS',                'Cannot combine given arrays.'                                              );
    define ('CANNOT_COMBINE_ARRAYS_FIX',            'Please make sure your variables are both arrays.'                          );
    define ('CANNOT_WRITE_HTACCESS',                'Cannot write .htaccess file!'                                              );
    define ('CANNOT_WRITE_HTACCESS_FIX',            'Please "chmod 0777 .htaccess" in Linux, to set proper permissions.'        );
    define ('FILE_NOT_WRITEABLE',                   'File is not writeable.'                                                    );
    define ('FILE_NOT_WRITEABLE_FIX',               'Set proper permissions before attempting to write to this file!'           );
	define ('CSS_FILE_NOT_FOUND',               	'The CSS file does not exist, or the passed param is not a string.'         );
	define ('CSS_FILE_NOT_FOUND_FIX',	            'Check the path you passed, or the parameter type!'           				);
	define ('CLASS_NOT_FOUND',                      'The requested class was not found. Cannot instantiate object!'             );
	define ('CLASS_NOT_FOUND_FIX',                  'Please make sure the files were loaded, or activate the requested module!' );
	define ('CANNOT_ADD_NON_STRING_TITLE',          'Cannot add non-string title.'                                              );
	define ('CANNOT_ADD_NON_STRING_TITLE_FIX',      'Make sure you (string) cast it first!'                                     );
	define ('CHECKED_PATH_NOT_DIRECTORY',           'The given path is not a directory.'                                        );
	define ('CHECKED_PATH_NOT_DIRECTORY_FIX',       'Please give a correct path to the directory you wish to check.'            );
	define ('VIEW_FILE_DIRECTLY_DENIED',            'Oh, wait ... this is a hacking attempt! Damn, we gotcha! ...'              );
	define ('VIEW_FILE_DIRECTLY_DENIED_FIX',        'You could go for a walk, drink a beer, get a life!'                        );
	define ('HACKING_ATTEMPT_BANG_YOU_DEAD',        'Bang! You ... DEAD. Life sux when we\'re having fun ...'                   );
	define ('OFFSET_KEY_NOT_SET',                   'The key you requested was not set!'                                        );
	define ('OFFSET_KEY_NOT_SET_FIX',               'Do a checking before trying to use an key that was not set!'               );
	define ('CANNOT_CALL_METHOD_STRING',            'Cannot call requested object method!'                                      );
	define ('CANNOT_CALL_METHOD_STRING_FIX',        'Make sure you do not have a typo in that code.'                            );
	define ('CSS_FILE_TAG_NOT_SET',					'The CSS file tag you wanted to unset, was not set!'						);
	define ('CSS_FILE_TAG_NOT_SET_FIX',				'Please do not try to remove a CSS file that was not set!'					);
	define ('CSS_FILE_PATH_NOT_SET',				'The CSS file path you wanted to unset, was not set!'						);
	define ('CSS_FILE_PATH_NOT_SET_FIX',			'Please do not try to remove a CSS file that was not set!'					);
	define ('JSS_FILE_TAG_NOT_SET',                 'The JSS file tag you wanted to unset, was not set!'                        );
    define ('JSS_FILE_TAG_NOT_SET_FIX',             'Please do not try to remove a JSS file that was not set!'                  );
	define ('JSS_FILE_PATH_NOT_SET',                'The JSS file path you wanted to unset, was not set!'                       );
    define ('JSS_FILE_PATH_NOT_SET_FIX',            'Please do not try to remove a JSS file that was not set!'                  );
	define ('META_TAG_NOT_SET',                     'The meta tag you want to remove, was not set!'                             );
	define ('META_TAG_NOT_SET_FIX',                 'This is a coding error. Check you code!'                                   );
	define ('OBJECT_NOT_FOUND_OR_INSTANTIATED',     'Requested object class was not found or object was not instantiated!'      );
	define ('OBJECT_NOT_FOUND_OR_INSTANTIATED_FIX', 'Make sure you do not have an error in your code, and file a bug after.'    );
	define ('CANNOT_TOUCH_FILE',                    'Cannot touch requested file path. Maybe not a file or permission problem.' );
	define ('CANNOT_TOUCH_FILE_FIX',                'Please check file permissions.'                                            );
	define ('COPY_OPERATION_FAILED',                'The copy operation failed.'                                                );
	define ('COPY_OPERATION_FAILED_FIX',            'Theoretically, this should be a permission problem, but please check!'     );
	define ('RENAME_OPERATION_FAILED',              'The rename operation failed.'                                              );
	define ('RENAME_OPERATION_FAILED_FIX',          'Theoretically, this should be a permission problem, but please check!'     );
	define ('CANNOT_MODIFY_SESSION_CACHE',          'Cannot modify the session cache expire time.'                              );
	define ('CANNOT_MODIFY_SESSION_CACHE_FIX',      'A config parameter may be wrong. Please check that!'                       );
	define ('METHOD_NAME_NOT_MAPPED',               'Requested PHP function was not mapped to a DataType!'                      );
	define ('CANNOT_WRITE_FILE',                    'Cannot write content to passed file path!'                                 );
	define ('CANNOT_WRITE_FILE_FIX',                'Make sure the path can be written!'                                        );
	define ('PROPERTY_NOT_SET',						'The property was not set!');
	define ('PROPERTY_NOT_SET_FIX',					'Make sure you first set a property before using it!');
?>
